import type { Metadata } from 'next'
import { Noto_Sans_Kannada, Poppins } from 'next/font/google'
import './globals.css'
import ThemeProvider from '@/utils/ThemeProvider'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { routing } from '@/i18n/routing'
import { notFound } from 'next/navigation'

const poppinsSans = Poppins({
  variable: '--font-poppins-sans',
  subsets: ['latin'],
  weight: ['400', '700'],
})

const notoSansKannada = Noto_Sans_Kannada({
  variable: '--font-noto-sans-kannada',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: 'Nishanth Portfolio',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${poppinsSans.variable} ${notoSansKannada.variable} antialiased`}>
        <NextIntlClientProvider>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
            {children}
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
